### ISSUE TITLE
Add an additional maintainer for this repository

### ISSUE THREAD

**Issue by zkrolikowski-vl** [conda-forge/pandas-stubs-feedstock#65]
Issue:

Please add Joanna Sendorek (https://github.com/joannasendorek) as an additional maintainer of this repository.

She should have the same permission level as myself.

**Comment by zkrolikowski-vl** [comment]
Sorry for pointing you out CJ but that's the easiest and most reliable way to get attention. :D 

Thanks in advance.

**Comment by CJ-Wright** [comment]
Why is this coming to me personally?

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Comment by zkrolikowski-vl** [comment]
@CJ-Wright Sorry. It wasn't meant for you personally. I picked you from the owners by random.

Is there a channel of communication for such requests? Should I use gitter or the mailing list?

**Comment by CJ-Wright** [comment]
You yourself have write permissions to the repo, please read the documentation and make a pull request adding people to the recipe-maintainers.

Assigning this to a single person who is not party to this repo is an abuse of the github notification system. If you need help in the future ping one of the help teams or core.

I am making this comment solely in my personal capacity and am not conveying any rights to any intellectual property of any third parties.

**Comment by zkrolikowski-vl** [comment]
Thanks and again sorry for notifying you. Will resolve this through recipe-maintainers.
